### PR TITLE
Add hclust heatmap and optimal order to README

### PR DESCRIPTION
**Pull request by kescobo**
Discussed in #152 and related issues, having a `hclust()` dendrogram + heatmap is often useful. I'm not sure it warrants a separate recipe, but I added an example to the README here, and also show off the new `branchorder=:optimal` option for `hclust` added in https://github.com/JuliaStats/Clustering.jl/pull/170 since it's primarily "optimal" in the sense that it makes the visualization prettier. 

In [this issue](https://github.com/BioJulia/Microbiome.jl/issues/19) ages ago we talked about putting that code into the plots package, but they were happy to take it and the PR made it a lot better IMO. 

If you'd prefer that I actually make a recipe for something like `heatmap(matrix, hclust)` that does this, I'd be happy to do that instead.

NOTE: Do not merge until there's a `Clustering.jl` release that includes that PR

Here's the added content for reference:

```julia
using Clustering
using Distances
using StatsPlots
using Random

n = 40

mat = zeros(Int, n, n)
# create banded matrix
for i in 1:n
    last = minimum([i+Int(floor(n/5)), n])
    for j in i:last
        mat[i,j] = 1
    end
end

# randomize order
mat = mat[:, randperm(n)]
dm = pairwise(Euclidean(), mat, dims=2)

# normal ordering
hcl1 = hclust(dm, linkage=:average)
plot(
    plot(hcl1, xticks=false),
    heatmap(mat[:, hcl1.order], colorbar=false, xticks=(1:n, ["$i" for i in hcl1.order])),
    layout=grid(2,1, heights=[0.2,0.8])
    )
```

heatmap dendrogram non-optimal

Compare to:

```julia
# optimal ordering
hcl2 = hclust(dm, linkage=:average, branchorder=:optimal)
plot(
    plot(hcl2, xticks=false),
    heatmap(mat[:, hcl2.order], colorbar=false, xticks=(1:n, ["$i" for i in hcl2.order])),
    layout=grid(2,1, heights=[0.2,0.8])
    )
```

heatmap dendrogram optimal

### CODE REVIEW

**Comment by versipellis** [comment]
Hey @kescobo - what's the status of this PR? Anything I can help with if I have some free time?

**Comment by kescobo** [comment]
It should be ready to go as https://github.com/JuliaStats/Clustering.jl/pull/170 was merged and released. That said, it doesn't actually add any code, just shows off the optimal ordering functionality of `hclust()`. I'd be happy for this to get incorporated with #214

**Comment by mkborregaard** [comment]
so this is ready for review and merge?

**Comment by kescobo** [comment]
@mkborregaard Yup! It's just an addition to the README though.

**Pull request merged**
