### PR TITLE
Better hover text for boxplots

### PR DESCRIPTION
**Pull request by diegozea**
This add hover text for the boxplot.

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Can you add some before and after pictures?

**Comment by diegozea** [comment]
Sure! :)

**Before**
*there was no hover text :/*

OLD

**After**
*it's a little more informative :)*

NEW

NEW_2

**Comment by diegozea** [comment]
Hi! Is something more need to merge this PR? Best,

**Comment by daschw** [comment]
How does this affect boxplots in GR or PGFPlotsX?

**Comment by diegozea** [comment]
It should not affect those.  Basically, this PR adds another series (`path`) with no visible elements (`linewidth := 0`) but with hover texts. This is an example for *GR* and *PGFPlotsX*:
       
image

**Comment by daschw** [comment]
OK, great, thanks a lot!

**Comment by diegozea** [comment]
You're welcome! Thanks!

**Pull request merged**
